<?php

return [
    /*
    | Only lowercase ASCII letters, numbers, and hyphens are accepted by the
    | application rule. Keep infrastructure and product-owned labels here so
    | they can never be allocated to a customer.
    */
    'reserved_subdomains' => [
        'account',
        'accounts',
        'admin',
        'api',
        'app',
        'assets',
        'auth',
        'autoconfig',
        'autodiscover',
        'billing',
        'blog',
        'cdn',
        'cpanel',
        'cpcalendars',
        'cpcontacts',
        'dashboard',
        'demo',
        'dev',
        'dns',
        'docs',
        'files',
        'ftp',
        'help',
        'host',
        'imap',
        'localhost',
        'login',
        'mail',
        'media',
        'mqtt',
        'mx',
        'ns1',
        'ns2',
        'pop',
        'pop3',
        'portal',
        'register',
        'root',
        'server',
        'sftp',
        'shop',
        'smtp',
        'ssh',
        'staging',
        'static',
        'status',
        'storage',
        'store',
        'support',
        'test',
        'webdisk',
        'webmail',
        'whm',
        'www',
    ],

    'webhook' => [
        'path'                    => env('SOFTWARE_ONLINE_WEBHOOK_PATH', 'api/webhooks/ps-web/tenant-events'),
        'timestamp_tolerance'     => (int) env('SOFTWARE_ONLINE_WEBHOOK_TOLERANCE', 300),
    ],
];
